#!/usr/bin/env python3

import os
import json


# 'splitall' comes from: https://www.oreilly.com/library/view/python-cookbook/0596001673/ch04s16.html
def splitall(path):
    allparts = []
    while 1:
        parts = os.path.split(path)
        if parts[0] == path:  # sentinel for absolute paths
            allparts.insert(0, parts[0])
            break
        elif parts[1] == path:  # sentinel for relative paths
            allparts.insert(0, parts[1])
            break
        else:
            path = parts[0]
            allparts.insert(0, parts[1])
    return allparts


includes = []

for root, _, files in os.walk("containers"):
    dirs = splitall(root)
    for file in files:
        if len(dirs) == 3 and file == "Dockerfile":
            includes.append({
                "container": dirs[1],
                "version": dirs[2],
                "skip": {
                    "aarch64": os.path.isfile(root + "/skip.aarch64")
                },
            })

matrix = {
    "include": includes,
}

matrix = json.dumps(matrix)
print(f'matrix={matrix}')
